root: ./docs/.

structure:
  readme: ../README.md
  summary: summary.md

redirects:
  sessions-and-multiple-connections: ./features/sessions-and-multiple-connections.md
  codelens: ./features/codelens.md
  executing-queries: features/executing-queries.md