version: '3.1'

services:
  db:
    image: microsoft/mssql-server-linux
    restart: unless-stopped
    ports:
      - '1433:1433'
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./import-data.sh:/import-data.sh
      - ./setup.sql:/setup.sql
    command: bash /entrypoint.sh
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: root(!)Password
      # USER: sa
